export const bookGenres = [
    'Historical Fiction',
    'Classics',
    'Children\'s Fiction',
    'Science Fiction',
    'Epic',
    'Adventure',
    'Fantasy',
    'Mystery',
    'Thriller',
    'Romance',
    'Non-Fiction',
    'Biography',
    'Autobiography',
    'Horror',
    'Self-Help',
    'Literary Fiction',
    'Dystopian',
    'Memoir',
    'Young Adult',
    'Humor',
    'Short Stories',
    'Graphic Novel',
    'Poetry',
    'Science',
    'Art',
    'Cookbook',
    'Travel',
    'History',
    'Religion',
    'Spirituality',
    'Sports',
    'Anthology',
    'Crime',
    'Western',
    'Philosophy',
    'Psychology',
    'Business',
    'Economics',
    'Politics',
    'Music',
]